const types = {
    FETCH_FROM_LOCAL_STORAGE: 'FETCH_FROM_LOCAL_STORAGE',
    SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',

    SAVE_NOTE: 'SAVE_NOTE_HANDLER',
    CANCEL_NOTE_HANDLER: 'CANCEL_NOTE_HANDLER',

    FIELD_BLUR_HANDLER: 'FIELD_BLUR_HANDLER',

    UNDO_HANDLER: 'UNDO_HANDLER',
    REDO_HANDLER: 'REDO_HANDLER'
}

export default types    